# Generated by Django 4.0.2 on 2022-03-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspaces', '0003_alter_assignment_is_active_alter_board_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='board',
            name='board_number',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_number',
        ),
    ]
